# --------------------User Testing--------------------
GET https://gorest.co.in/public/v1/users?page=1&per_page=100
###

GET https://gorest.co.in/public/v1/users/3069
###

POST https://gorest.co.in/public/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer baab25ae311ca6c3737a36fc87d76b24da71f067d290a965dea6eb07cd04b6de


{        
    "name": "tita",
    "email": "titazahra@gmail.com",
    "gender": "female",
    "status": "active"
}


###

DELETE https://gorest.co.in/public/v1/users/3154
Authorization: Bearer baab25ae311ca6c3737a36fc87d76b24da71f067d290a965dea6eb07cd04b6de
###

PATCH  https://gorest.co.in/public/v1/users/3069 HTTP/1.1
Content-Type: application/json
Authorization: Bearer baab25ae311ca6c3737a36fc87d76b24da71f067d290a965dea6eb07cd04b6de

{
    "name": "Archan Talwar Updated",
    "email": "talwar_archan@labadie.net",
    "gender": "male",
    "status": "active"
}
###

# --------------------Products Testing--------------------
GET https://sbd-kelompok-2.vercel.app/product
###

GET https://sbd-kelompok-2.vercel.app/product/63a2af04c88ec0ff9b0a8349
###

POST https://sbd-kelompok-2.vercel.app/product HTTP/1.1
Content-Type: application/json

{
    "title": "Ir-192",
    "description": "this product usually used for industrial NDT",
    "left": "Rp. 3.500.000,-",
    "right": "Jakarta",
    "image": "https://www.oserix.com/web/image/887/ir_attachment_2963.png"
}
###

DELETE https://sbd-kelompok-2.vercel.app/product/63a6fe6107e0672d57d36c97
###

PATCH https://sbd-kelompok-2.vercel.app/product/63a6fe6107e0672d57d36c97 HTTP/1.1
Content-Type: application/json

{
    "title": "Ir-192 updated",
    "description": "this product usually used for industrial NDT",
    "left": "Rp. 2.500.000,-",
    "right": "Batam",
    "image": "https://www.oserix.com/web/image/887/ir_attachment_2963.png"
}